### ISSUE TITLE
"[CoreBluetooth] XPC connection invalid" error 

### ISSUE THREAD

**Issue by Sikandarkhan** [NordicSemiconductor/IOS-nRF-Toolbox#103]
Greetings,
Once the app has launched, I'm getting an error in the Xcode console that says: "[CoreBluetooth] XPC connection invalid"

Below is what I'm using hardware/software wise:

macOS Catalina v10.15.4
Xcode v11.5
iPhone 6 -- iOS v12.3

I also made sure to add the `NSBluetoothAlwaysUsageDescription` and `NSBluetoothPeripheralUsageDescription` permissions to the *info.plist* file.

**Comment by philips77** [comment]
This is just a warning. It happens when a `CBCentralManager` instance is disposed. In the app and in our libraries we often use one manager instance per profile to separate functionality and allow multiple delegates. iOS would prefer a singleton which lives as long as the app, but everything works as expected with multiple instances.

**Comment by Sikandarkhan** [comment]
After the update, I am not getting values for systolic and diastolic. Only seeing battery %


![IMG_3ACD5297807D-1](https://user-images.githubusercontent.com/7334929/93662540-958b9e80-fa7e-11ea-8afb-e47a29126207.jpeg)


please suggest me on this.

**Comment by Sikandarkhan** [comment]
I realised the issue is with Bluetooth pairing process. After unpairing and pairing to Bluetooth this code started working appropriately. 

I was spending days and days to debug code and writing queries to firmware developers.

Glad that this simple fix resolved my query. 
![IMG_599869406662-1](https://user-images.githubusercontent.com/7334929/93664029-71818a80-fa89-11ea-9950-0fd80c29edf8.jpeg)




Hope this answer will be helpful to others in future.
