### ISSUE TITLE
UART App Not Sending EOL

### ISSUE THREAD

**Issue by dbeckwith01** [NordicSemiconductor/IOS-nRF-Toolbox#104]
I'm using nRF Toolbox v5.0.2 with the Nordic BLE CLI on a DK.  When I create and send a text command the command is sent (confirmed on the logs) but the EOL doesn't seem to be sent to execute the command on the CLI.

I have gotten around this by creating a second command to send a hex 0x0D down to the device.

**Comment by philips77** [comment]
You need to type a new line at the end of the first command. The eol selection defined to what values the new lines are encoded.

**Comment by dbeckwith01** [comment]
@philips77 Can you please provide a little more detail.  I tried adding a new line at the end of the command and when I come back the new line is no longer in the command window.

**Comment by philips77** [comment]
@NickKibish ?
