### ISSUE TITLE
Project setup is wrong

### ISSUE THREAD

**Issue by ramunasjurgilas** [NordicSemiconductor/IOS-nRF-Toolbox#108]
Project setup is wrong, that after project checkout needs to execute terminal command: **pod update** . 

3rd party libs should be committed together with project. In this case cocoapods would not be needed.

**Comment by philips77** [comment]
On the other hand, not committing *Pods* folder makes the repository cleaner. Required dependencies can easily be downloaded with 
```
pod install
```
and we save sending huge number of files we are no in control of. I would say it's a matter of ones choice.
