### ISSUE TITLE
MCUManager vs SwiftCBOR target difference build error

### ISSUE THREAD

**Issue by Dario-GoldenSpear** [NordicSemiconductor/IOS-nRF-Toolbox#122]
Hi,

I am trying to build the latest version from the master branch: https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/commit/53605f540112b1ca9b2820bdb752039d3c16f4b3

(same problem if I try the latest release: https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/tree/5.0.7)

Xcode version: 13.2.1

After running `pod install` and updating the targets versions to 12.0 as suggested by Xcode:
![nRF-Toolbox-target-update](https://user-images.githubusercontent.com/58740705/153767903-ef4f943a-b8c8-4a88-bf3e-65e3d58feba1.png)

When trying to build I get the following error:
```
Build target McuManager with configuration Debug
error: The package product 'SwiftCBOR' requires minimum platform version 10.0 for the iOS platform, but this target supports 9.0 (in target 'McuManager' from project 'McuManager')
```

To the best of my knowledge the problem is that SwiftCBOR's project has been updated 2 months ago, setting the package's min. platform version to 10.0:
https://github.com/unrelentingtech/SwiftCBOR/blob/master/Package.swift

while McuManager's package is still set to 9.0 (develop branch):
https://github.com/NickKibish/IOS-nRF-Connect-Device-Manager/blob/develop/Package.swift

Also in the master branch:
https://github.com/NickKibish/IOS-nRF-Connect-Device-Manager/blob/master/Package.swift

**Comment by dinesharjani** [comment]
Hi @Dario-GoldenSpear - thanks for making us aware of this.

In the Device Manager library we targeted an earlier version of CBOR that doesn't require the higher minimum platform version.

**Comment by dinesharjani** [comment]
@Dario-GoldenSpear making a fix. Give me a few minutes.

**Comment by dinesharjani** [comment]
@Dario-GoldenSpear I think we fixed the issue. Let us know.

**Comment by Dario-GoldenSpear** [comment]
@dinesharjani yes, this fix solved the issue, thanks!.
