### ISSUE TITLE
Type "com.pkware.zip-archive" was expected to be declared and imported

### ISSUE THREAD

**Issue by Emanuele9xx** [NordicSemiconductor/IOS-nRF-Toolbox#141]
The toolbox started correctly, I try to test a fw update for a DFU device, I find it via ble, but when I choose the DFU Distribution package I see this error:
<img width="692" alt="image" src="https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/assets/152969323/2091d3e5-b55a-4794-bbf1-1d14fb44ad54">

**Comment by knakul853** [comment]
getting the same error, any update on this
