### ISSUE TITLE
Project will not build 'iOSDFULibrary-swift.h' file not found"

### ISSUE THREAD

**Issue by crhayden** [NordicSemiconductor/IOS-nRF-Toolbox#22]
this project fails to build when I try and run it on an iPhone. 

The error is I get is "nRF Toolbox/DFU/FileSelection/FileTypeViewController.h:24:9: 'iOSDFULibrary-swift.h' file not found"

It also was missing the SWRevealViewController.h file but I was able to fix that by creating a new SWRevealViewController.h and grabbing the code from here:   
https://github.com/John-Lluch/SWRevealViewController/tree/master/SWRevealViewController

**Comment by mostafaberg** [comment]
Hey!, you seem so have forgotten to run `pod install`, you shouldn't add the dependencies manually like you did.

I recommend deleting the project, cloning a new clean version, then in your terminal go to the project root where the `Podfile` exists and run the `pod install` command, your project will build afterwards!
