### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by gkaimakas** [NordicSemiconductor/IOS-nRF-Toolbox#24]
When can we expect Swift 3.0 support?

**Comment by mostafaberg** [comment]
We are currently in the process of Swift 3.0 migration and are working hard to bring out the latest Swift version of the project as soon as we can, we do not have an exact date but it should be out soon, we will update you along the way will close this issue once the new version is out!

thanks for your patience

**Comment by mostafaberg** [comment]
[Swift 3.0 is now Supported!](https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/releases/tag/4.1.0)
