### ISSUE TITLE
Crashes when copying DFU file from Email

### ISSUE THREAD

**Issue by vandrewal** [NordicSemiconductor/IOS-nRF-Toolbox#25]
Version 4.0.4, iPad Air 2, iOS 9.3.5

I longclick the DFU attachment in the Email app, and select "Copy to nRF Toolbox". The splash screen appears and then nRF Toolbox crashes. No files can be found in the "Inbox" folder under "User Files" after restarting the nRF Toolbox.

I have experienced the same problem on two devices, and this seems to be the exact same problem that user "develooop" describes here: https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/issues/23

**Comment by mostafaberg** [comment]
Issue is resolved and will be ready in the coming update, we have already submitted to the app store and will update the changes here very soon!
