### ISSUE TITLE
Crashing during DFU

### ISSUE THREAD

**Issue by Redguy1986** [NordicSemiconductor/IOS-nRF-Toolbox#26]
Version 4.1.0. iPhone 5c, IOS 9.3.4
I choose DFU mode, then push button "Select Device". The app crashes down.
I choose UART mode, I have the same behavior after "Connect" button pressed.
I tried it in app from official AppStore

**Comment by Redguy1986** [comment]
When I tried the app on iPhone 5s with iOS 10 it works properly.

**Comment by mostafaberg** [comment]
Ok let's see, you're saying it crashes only on iOS10 ?

**Comment by Redguy1986** [comment]
No.
It crashes on iOS 9.3.4.
I've tried it on iOS 10, and the app works well.
So, it depends on iOS version

**Comment by mostafaberg** [comment]
Ok so it works ok here on iOS 9, testing on 10 to verify, but if it works here on iOS 9 ..

Can you help out by attaching your device crash logs ?

**Comment by Redguy1986** [comment]
How can I help you?
I tried to get logs in iTools program.
Look at these files:
[itools_log.txt](https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/files/515606/itools_log.txt)
[nRF Toolbox-2016-10-07-121411.ips.txt](https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/files/515607/nRF.Toolbox-2016-10-07-121411.ips.txt)
[nRF Toolbox-2016-10-07-121438.ips.txt](https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/files/515605/nRF.Toolbox-2016-10-07-121438.ips.txt)
Are they useful for you?

**Comment by mostafaberg** [comment]
They are not symbolicated so it's a bit hard to know what happened exactly.
Can you plug it into XCode, and export the last crash report from the device manager there and send me that file ? it's ok if that's not symbolicated too as long as you are using the exact last version form the app store

**Comment by Redguy1986** [comment]
I'm sorry, I can't use Xcode. I'm an application user, not an iOS developer. Besides, I use Windows7 on my PC and I have no possibility to use apple features or programs.

**Comment by mostafaberg** [comment]
Ah ok, thought you had a development environment, ok i'll try to reproduce here and see what I can do, it doesn't reproduce that's the problem, but will experiment and try to see if I can resym your crashes so I can understand what's going on, will keep you updated.
Thanks a lot for your help!

**Comment by paweljankowski** [comment]
This crash occurs on iOS 10.1 (on iOS 10 works perfectly). I was able to download sources and launch nRFTToolbox and the issue is with class `NORScannerViewController` line 168:
```
Could not cast value of type 'NSKVONotifying_CBPeripheral' (0x174300bd0) to 'nRF_Toolbox.NORScannedPeripheral' (0x100163e28).
2016-10-26 08:34:16.326754 nRF Toolbox[2206:577147] Could not cast value of type 'NSKVONotifying_CBPeripheral' (0x174300bd0) to 'nRF_Toolbox.NORScannedPeripheral' (0x100163e28).
```

**Comment by Redguy1986** [comment]
When I updated iOS to 10 version this issue was still there.
Right now I've updated NRFToolbox to 4.1.1 version from appstore and the issue disappeared.
Thank you.

**Comment by paweljankowski** [comment]
On iOS10.1 crash still exists.

**Comment by paweljankowski** [comment]
Can you release this fix to the AppStore?

**Comment by philips77** [comment]
We will publish it tomorrow or on Wednesday, sorry for the delay, but I'm also working on new version of DFU library and need to finish it before.
