### ISSUE TITLE
BLE-UART String Send

### ISSUE THREAD

**Issue by lauleehong** [NordicSemiconductor/IOS-nRF-Toolbox#28]
Hi,

Tested using iOS 10.1

Connecting to my device on UART-BLE, and then sending a string 'ACK' or any arbitrary characters would send up with a random hexstring sent. Sending the same character string 'ACK' twice shows on the log 2 different hexstrings are sent: for example "0x000abc" and "0x000abd". 

I've tested my hardware and firmware against the Android version of the nRF Toolbox, and is proven to be working normally.

**Comment by mostafaberg** [comment]
Hi !, sorry to hear that, can you send us some concrete values we can test against? and show what should be displayed and what was displayed instead, will take a look into it when i have something to test against!, thanks!

**Comment by lauleehong** [comment]
Hi, thanks for looking into this. 
Below is a screenshot from my iPhone: 

![img_log](https://cloud.githubusercontent.com/assets/15611087/19330076/fe9b8ce8-9090-11e6-9952-79c4f5557f24.jpg)
![img_config](https://cloud.githubusercontent.com/assets/15611087/19330077/feaf3c02-9090-11e6-914f-97ec77e3cf4a.jpg)

**Comment by philips77** [comment]
@mostafaberg could you look into the log here, it should not print
'Optional', and should print text as string on Application level and as
bytes on debug.

**Comment by mostafaberg** [comment]
@lauleehong Thanks for the detailed screenshot, will look int to that soon !
@philips77 Noted, will get that done too!
