### ISSUE TITLE
Glucose measurement is in mmol/l but it is really in KG/L?

### ISSUE THREAD

**Issue by jpboro** [NordicSemiconductor/IOS-nRF-Toolbox#3]
I used a glucometer with bluetooth  to send the reading to the app. I compared my reading from the glucometer to the data that is shown by the app and found that the app converts the glucose measurement to KG/L and not to mmol/l? The reading on the glucometer is in mg/dl so when I multiplied the app reading by 100000 , that is when they are the same. Also the parsed time is late by an hour. Right now I don't have an idea why but I'm checking out the downloaded code. Just a heads up.

**Comment by philips77** [comment]
Released in version 2.5. Thank you for bug report!
