### ISSUE TITLE
DFU not working

### ISSUE THREAD

**Issue by andrewbollen** [NordicSemiconductor/IOS-nRF-Toolbox#33]
On pressing upload, app crashes and the configurable settings (number of packets and External MCP DFU) are reset to 12 and OFF respectively. We require number of packets to be 1, and External MCP DFU to be ON. We did not have this issue in v3.0.1.

**Comment by mostafaberg** [comment]
Hi @andrewbollen , can you try updating to the latest DFU Library version in the app and rebuild ?
modify the Podfile so this line:
`pod 'iOSDFULibrary', :git => 'https://github.com/nordicsemiconductor/ios-pods-dfu-library', :branch => 'Version3'`

becomes:

`pod 'iOSDFULibrary', '~> 3.0'`

then run `pod update`

if the issue still persists please let us know

**Comment by andrewbollen** [comment]
Thankyou @mostafaberg, the latest update to nRF-Toolbox does not appear to have the same problem, and we have been able to correctly upload our firmware. Thanks for the response.
