### ISSUE TITLE
Single bank DFU upload

### ISSUE THREAD

**Issue by shayo** [NordicSemiconductor/IOS-nRF-Toolbox#34]
Seems like DFU upload doesn't support large files (even though they fit with single bank bootloader).

**Comment by mostafaberg** [comment]
Hi @shayo we will need more details to be able to help, like what are you experiencing ? and what is expected to happen but doesn't ? and any error codes, log messages would be good to have

**Comment by mostafaberg** [comment]
Closing as got no response for a few months
