### ISSUE TITLE
DFU does not work on iOS 10

### ISSUE THREAD

**Issue by quandosale** [NordicSemiconductor/IOS-nRF-Toolbox#37]
Hi
I'm having the same issue with this
https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/issues/32

When I click on Upload after choosing packet zip file and nordic device, it seems not connect to the device
From the link above, he seems to have solved the problem, and I 'd like to solve that issue

It would be very great if you can help me

**Comment by mostafaberg** [comment]
Hi Quandosale, do you still have an issue ?

**Comment by quandosale** [comment]
Hi, I solved the issue on my end. Thanks

**Comment by mostafaberg** [comment]
That's good news, so sorry for the late response from our side, will close that now :)
