### ISSUE TITLE
DFU. Operation not permitted

### ISSUE THREAD

**Issue by Xiahaiquan** [NordicSemiconductor/IOS-nRF-Toolbox#45]
HI 
When I upload the Zip file,  remind Operation not permitted . what's the reason?
Do anyone have the same problem 。

**Comment by philips77** [comment]
It depends. You have to give more details. Which SDK are you using, what ZIP file, etc.
Without it we can't help you. There is a lot of reasons you got this issue.

**Comment by Xiahaiquan** [comment]
I found the reason. I don't have config DFU  environment. Thank you.
![2018-01-12 17 02 35](https://user-images.githubusercontent.com/16540292/34867309-a08317a6-f7ba-11e7-9d2f-c9ae7e232b35.png)

**Comment by Xiahaiquan** [comment]
HI
 when I  used DFUModel ，it is success. after I scan CBPeripheral use the CBCentralManager. But the `**- (void) centralManager:(CBCentralManager*) manager didPeripheralSelected:(CBPeripheral*) peripheral;** `this method in MyViewController it not work.
How can I fix it? Thank you

**Comment by mostafaberg** [comment]
Seems like your issue has been resolved, and you have asked a different question in the same thread, will close this one and if you still have another question please open a new issue :)
