### ISSUE TITLE
How do I integrate into objects-c projects?

### ISSUE THREAD

**Issue by Coder-Yfeng** [NordicSemiconductor/IOS-nRF-Toolbox#46]
My Obj-C projects is using Cocoapods and install iOSDFULibrary,but I Can't find the header file?
By the way, your Obj-C demo updateFirmware,the demo will crash;

**Comment by mostafaberg** [comment]
Good morning @Coder-Yfeng !
I'm a bit confused, is the issue related to the DFU Library or nRF Toolbox ?
and which objective C demo are you talking about ? all our codebase is in Swift :)

if you clarify a bit more we will be able to help, DFU Library works well with Objective-C and Swift

**Comment by Coder-Yfeng** [comment]
//

**Comment by Coder-Yfeng** [comment]
nRF-Toolbox obj-c demo,the demo will crash,
https://github.com/zhangferry/nRF-Toolbox
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Coder-Yfeng** [comment]
Single bank DFU upload

**Comment by mostafaberg** [comment]
@Coder-Yfeng This is not our project so we can't support that, we can only support our own products :)

**Comment by Coder-Yfeng** [comment]
ok!thank you
