### ISSUE TITLE
Unable to get UART connection on iOS 11

### ISSUE THREAD

**Issue by idokleinman** [NordicSemiconductor/IOS-nRF-Toolbox#49]
Could not connect to the nRF52840 preview DK eval kit running the ble_peripheral/ble_app_uart on iOS 11, tried on iPhone 7 and 8. Connection does not get established. 
Tried the app on an Android - no issues.

Please advise

**Comment by mostafaberg** [comment]
This seems weird indeed, if you try connecting with nRF Connect on iOS, are you able to find the uart TX and RX characteristics ?

**Comment by rectoyon** [comment]
i'm experiencing something similar. in ios 12 UART works on my iphone x but not on my ipad. In the ipad it sends a 0x01 0x00 byte array. But, writes never work.

this is only after I added the dfu service to my app.

Has anyone else been working with this combination?

**Comment by philips77** [comment]
Isn't it a cashing issue? Did you try to restart Bluetooth before connecting to wipe cache?
