### ISSUE TITLE
DFU firmware update text string broken

### ISSUE THREAD

**Issue by DG12** [NordicSemiconductor/IOS-nRF-Toolbox#52]
DFU firmware update texts string broken in version 4.4.4

The text beneath the "DEVICE FIRMWARE UPDATE"
is broken, shows only "U...ad"
![dfu-oops](https://user-images.githubusercontent.com/2365961/43746390-0b5ce554-99b2-11e8-8bba-9dc2b346f4d9.JPG)

PS "Firmware Update" title seems unnecessarily large (but hey that's just me.
especially since the gray text on the left article margin already says that.

Thanks for your support

**Comment by philips77** [comment]
Or was it by design? :)

**Comment by philips77** [comment]
I think we will eventually redesign toolboxes in some not-too-far future. Perhaps there will be space to fit at least "Upl...ad".

**Comment by NickKibish** [comment]
That screen was redesigned.
