### ISSUE TITLE
BLE Scanning Disabled

### ISSUE THREAD

**Issue by fillybrese** [NordicSemiconductor/IOS-nRF-Toolbox#53]
Also posted in iOS nRF Connect GitHub: https://github.com/NordicSemiconductor/IOS-nRF-Connect/issues/39

This has been a bug since first install of iOS 11, I believe. Now I'm on iOS 11.4.1 and both nRF Toolbox and nRF Connect are unusable. I am using iPhone 6S. Same device, no problems with nRF apps before this one.

The scanning list will only populate for a few seconds immediately after phone reboot.

Other BLE Scanning apps (i.e. Adafruit Bluefruit) seem to have problems too, but it is intermittent and can be reset by Bluetooth radio power cycle.

Force closing, re-opening does not fix. Force closing all apps does not fix.

I'm happy to share log files and help diagnose.

![img_5468](https://user-images.githubusercontent.com/5035050/44023538-381d6c6a-9f1d-11e8-863b-d1b3cdda172a.PNG)

**Comment by mostafaberg** [comment]
Let's handle this in NordicSemiconductor/IOS-nRF-Connect#39 to avoid losing information between tickets.
