### ISSUE TITLE
最新版的xcode10.2不兼容swift4.1

### ISSUE THREAD

**Issue by ColaColeChao** [NordicSemiconductor/IOS-nRF-Toolbox#59]
我们升级了xcode版本到xcode10.2，发现xcode10.2不支持swift4.1，只支持swift4.0、4.2和5.0，动态引用会和现有的pod导入的静态库冲突，不知道这个sdk能不能升级到swift5.0或者4.2版本？

**Comment by philips77** [comment]
That's an old issue. We just migrated to Xcode 12.5 and Swift 5.4.
