### ISSUE TITLE
any support for new dfu file type with zip?

### ISSUE THREAD

**Issue by jasonbu** [NordicSemiconductor/IOS-nRF-Toolbox#6]
seems android works well

**Comment by jasonbu** [comment]
I found that only application.bin in zip file work ok, trying

**Comment by huguesbr** [comment]
@jasonbu if you have a manifest with it, it should work...

**Comment by philips77** [comment]
Hi, I've just published the source code for the DFU Library: https://github.com/NordicSemiconductor/IOS-DFU-Library 
You should find this framework much easier to use now. The nRF Toolbox 3.0 (also published second ago) is showing how to use it. I'm really courious what do you think about the framework.
