### ISSUE TITLE
Xcode 10.2 Unsupported?

### ISSUE THREAD

**Issue by seancrowe5** [NordicSemiconductor/IOS-nRF-Toolbox#62]
It seems like the project won't compile in the latest version of Xcode. Anyone else having similar experience or am I doing something wrong here.

**Comment by dinesharjani** [comment]
Pull Request #65 should have fixed this, and I just merged it into master.

Please try pulling master and see if this works for you. nRF Toolbox now builds in Xcode 11 beta 3.

**Comment by JamesirYao** [comment]
@dinesharjani Cheers! Just get the problem yesterday. Didn't expect that can be fixed today!
