### ISSUE TITLE
Not disconnecting device in UART

### ISSUE THREAD

**Issue by sandhu0409** [NordicSemiconductor/IOS-nRF-Toolbox#64]
First time it shows all BLE devices. when I connected with one device and sending data works perfectly. But when I will disconnect and try to reconnect it didn't show in scanning peripheral list even other devices not able to find that ble device.

**Comment by philips77** [comment]
How about killing the nRF Toolbox app? Or restarting the phone/Bluetooth?
Seems like the device is still connected after you click disconnect, for some reason.

**Comment by sandhu0409** [comment]
Yeah after restarting bluetooth it works fine. But after reconnect issue remains the same.

**Comment by philips77** [comment]
Looks like the app, or some other app, is still using this connection after uart disconnected. Calling cancelConnection() method disconnects only the virtual connection, but if some other is still open, the iOS will keep the physical Bluetooth link open. To be sure that the device disconnects you should implement disconnect feature on your peripheral side, e.g. after sending some op code.

**Comment by sandhu0409** [comment]
I have disconnected it but still its not working

**Comment by sandhu0409** [comment]
I think Apple not disconnected main Ble connection and stores in Cache. Don't know its Apple bug or something else

**Comment by philips77** [comment]
I'm closing the issue as it was related to older version of the app.
