### ISSUE TITLE
we are developing some solution where we want to password protect BLE functionality based on individual device (in iOS App)

### ISSUE THREAD

**Issue by Smitgamit** [NordicSemiconductor/IOS-nRF-Toolbox#66]
"We are developing some solution where we want to password protect BLE functionality based on the individual device. It is very important to connect each device with some security. If you have any other option through which user can connect securely requesting you to share the way, where I want only one user to connect to the device with some security using passkey or pin"

(I need this type of functionality in iOS App).
![ble](https://user-images.githubusercontent.com/25656131/61575553-8d3a7b00-aaea-11e9-9bbd-83c856fab013.png)

I need secure pairing from the iOS App is it possible?
Please help if anybody have any idea?

**Comment by philips77** [comment]
Please ask your question on Nordic DevZone, add is not an issue in nRF Toolbox. Our support team will gladly help.
