### ISSUE TITLE
Bluetooth disconnects when Strip is inserted to measure BGM.

### ISSUE THREAD

**Issue by anugrah-sebastian** [NordicSemiconductor/IOS-nRF-Toolbox#91]
After successful pairing in BGM and when strip is inserted bluetooth disconnects. We have to press connect after measuring Blood glucose then Bluetooth connectivity happens.

**Comment by anugrah-sebastian** [comment]
@philips77 Why is it happening?

**Comment by philips77** [comment]
Hello,
Sorry for coming so late to you. I think it's the way your device works, and there's nothing that could be done from the mobile side.
