### ISSUE TITLE
Error on ModernIcon Usage

### ISSUE THREAD

**Issue by iOSUjjwal** [NordicSemiconductor/IOS-nRF-Toolbox#98]
I am not able to compile the code, I am getting errors on ModernIcon usage (see attached).
Xcode Version - 11.2.1
Swift Version - 5

Please advise.

![Screenshot 2020-07-02 at 8 37 33 PM](https://user-images.githubusercontent.com/32178515/86375862-de179500-bca3-11ea-87f8-b988f9fc29b0.png)

**Comment by aikudo** [comment]
I got the same error with 11.3.1. Have you try a newer Xcode? You might have to upgrade OSX to 10.15.4 to get the latest Xcode.  https://en.wikipedia.org/wiki/Xcode#12.x_series
