### ISSUE TITLE
iOS nRF ToolBox 5.0.1 UART

### ISSUE THREAD

**Issue by aikudo** [NordicSemiconductor/IOS-nRF-Toolbox#99]
I'm using nRF5_SDK_17.0.0_9d13099, ble_uart. I can connect to the UART on Android using nRF UART v2.0.
On iOS, I downloaded the  nRF ToolBox 5.0.1 app from Apple Store to a niphone 6 (12.4.6) and ipad 7 (13.5.1).
I couldn't connect to the UART from neither iOS devices.  I can scan, see the Nordic_UART on the list. Selecting that device shows " Connecting..." and it gets suck there. I believe no connection has made because the LED is still blinking. Immediately, I reconnect with an Android and it works. So I think there is something weird with the iOS app. I will try to compile previous versions to see if that would work.

Another test with Iphone 5 (10.3.4) shows it kind of making a connection because the LED did stop but it still got suck on "connecting..." Though I can press "cancel" and the LED resumes blinking. The two devices above couldn't even press the cancel button.

I just tested with an iphone 11 (13.4.1) and it worked fine. So I rebooted Iphone 6 and Ipad 7 and strangely got them to work. But it seems like there is a glitch with iphone6 as shown here. I also rebooted Iphone 5 and  it still  got suck at "connecting...", and would crashed when I press cancel.

![IMG_1061](https://user-images.githubusercontent.com/7387554/87368959-23558580-c534-11ea-817a-7dd36670fa2b.jpg)

I think the problem with iphone 6 is because it doesn't have the right fonts as listed in CommandImage.swift line 68--92. ModernIcon.swift line 58--56 returns a nil for iOS < 13.0 ? Sorry my computer is too old to install the proper version of Xcode to fix/test out the guess.

So I guess the this app requires iOS > 13.0 but in the appstore it says iOS 10.0.

**Comment by philips77** [comment]
Hello,
The UART will be rebuilt in the upcoming version. We will test it on iPhone 6 as well. Currently, however, @NickKibish is no vacations, so please be patient.
